env:
  node: true
  browser: true
  es6: true
  jest: true
extends:
  - "eslint:recommended"
  - "plugin:prettier/recommended"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - "jsdoc"
rules: {}
