/** Built-in extensions */
export { syntaxMystExtension } from './syntaxMyst.js'
export { admonitionsExtension } from './admonitions.js'
export { inlineMarkupExtension } from './inlineMarkup.js'
export { highlightExtension } from './highlight.js'
export { mathExtension } from './math.js'
export { figureExtension } from './figure.js'
export { tableExtension } from './table.js'
export { targetExtension } from './propagateTargets.js'
export { linkReferenceExtension } from './resolveLinks.js'
